#Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Install serve to serve the frontend files
RUN npm install -g serve

# Expose the port that the frontend will run on
EXPOSE 3000

# Run the frontend using serve
CMD ["serve", "-d", ".", "-p", "3000"]

