#Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that the backend will run on
EXPOSE 5000

# Set the environment variables for MongoDB URI
ENV MONGO_URI=your_mongodb_atlas_connection_string
ENV PORT=5000

# Run the backend with PM2
CMD ["npx", "pm2", "start", "server.js", "--name", "backend"]

